name: synoapi
description: synoapi
version: 0.2.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  logging: ^1.0.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  dio_cookie_manager: ^3.0.0

dev_dependencies:
  test: ^1.20.0
  build_runner: ^2.3.3
