name: synoapi
description: synoapi
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  logging: ^1.0.0
  json_annotation: ^4.0.0
  json_serializable: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
